---
language: ruby
sudo: required
services:
  - docker
script:
  - bundle exec rspec spec/acceptance
bundler_args: --without system_tests
matrix:
  include:
  - rvm: default
    env: LINT=metadata
    dist: trusty
    bundler_args:
    script: bundle exec rake metadata_lint
  - rvm: default
    env: BEAKER_set="ubuntu14-docker" TEST=mod
    dist: trusty
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/base*_spec.rb
